import type { Metadata } from 'next'
import { Inter, Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import Header from './header'
import Footer from './footer'

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body className={`${plusJakartaSans.className} flex flex-col min-h-screen`}>
        <Header/>
        <div className='flex-1'>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}
